server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: cm20020725
    driver-class-name: com.mysql.jdbc.Driver

#  application:
#    name: userservice #user服务的服务名称

#  cloud:
#    nacos:
#      server-addr: localhost:8845 #nacos服务地址（默认是8848）
#      discovery:
#        cluster-name: SH #集群名字，这里HZ代表杭州
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/


mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

