server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: cm20020725
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: orderservice #oder服务的服务名称

  cloud:
    nacos:
      server-addr: localhost:8845 #nacos服务地址（默认是8848）
      discovery:
        cluster-name: HZ #配置集群名称，也就是机房位置
#        namespace: e4739df6-2680-439b-acee-33e1202c0d6b #命名空间，填命名空间ID
        ephemeral: false #是否是临时实例



#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/


mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则


ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: #指定对某个服务进行饥饿加载
      - userservice


#日志配置
feign:
#  client:
#    config:
#      default:  # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLever: FULL #  日志级别


#连接池配置
  httpclient:
    enabled: true #支持HttpClient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #每个路径最大连接数
